### ISSUE TITLE
[Suggestion]: Keystrokes per minute

### ISSUE THREAD

**Issue by developomp** [bragefuglseth/keypunch#19]
**Is your suggestion related to a problem? Please describe.**

Average length of words vary significantly between languages and runs.

**Describe the solution you'd like**

Show `Keystrokes per minute` stats alongside `Words per minute` at the end of each run.

**Describe alternatives you've considered**

None

**Additional context**

None

- [x] This suggestion is compatible with the [GNOME Human Interface Guidelines](https://developer.gnome.org/hig)

**Comment by bragefuglseth** [comment]
Hi, and thanks for your suggestion! The term ["words per minute"](https://en.wikipedia.org/wiki/Words_per_minute) is actually slightly misleading, since it equates to roughly 5 characters/keystrokes. This is how most typing trainers, including Keypunch, calculate it. For languages with "compund characters", those can be "split up" into individual parts when calculating the WPM.

I'm unsure about the usefulness of showing KPM alongside WPM, since it's always going to be WPM * 5, and is harder to grasp / compare for the human brain. I'll close this for now, but leave the thread open for objections.

**Comment by developomp** [comment]
Can confirm:
https://github.com/bragefuglseth/keypunch/blob/b593cde6866843cb3f1fa04250b08f4a4d3647b1/src/text_utils.rs#L167

Thanks for the explanation!
