### ISSUE TITLE
Rework input system

### ISSUE THREAD

**Issue by bragefuglseth** [bragefuglseth/keypunch#24]
The current input system only listens to when text has been committed from the input method, and then pushes that directly to a string. For #22 and #8 to be implemented, we need to mark letters as partially typed more often:

- When preediting is being used.
- When the "alias" of a letter is being typed out. For example, the letter "œ" should be possible to enter by typing "oe". If "o" is typed, the letter should be marked as partially typed. Once it's fully typed, it's replaced with the proper letter in the "typed text" string. If something else is typed, the letter should be marked as incorrect, and the cursor should move to the next letter.

**Comment by idoric** [comment]
I thought about this proposal in connection with #22. There is a case that I had not talked about in #22 because it was not covered by Monkeytype, but which has its place with this new proposal: French quotation mark.

French quotation marks are used as follows: « + NNBSP + the quote + NNBSP + ». Example: « Ceci est une citation ». By default, when typing in a word processor configured for French, the character " is automatically replaced by « + (N)NBSP¹ or (N)NBSP + » depending on the context. Analyzing the context would be a much more ambitious proposition than expected. Fortunately I think there is another solution.

Keypunch wouldn’t need to act like a word processor, because it has an enormous facility compared to that type of software: it knows in advance the text that is going to be typed. It seems simpler to me to split the text into tokens and for each accept one or more sequences of characters. For example « C’est un œuf ! » would be cut into |« |C|’|e|s|t| |u|n| |œ|u|f| !| »|, then |« | would be validated with « + NNBSP, « + NBSP or ", |C| would (only) be validated with C, |’| would be validated with ’ or ', |œ| with œ or o + e, | !| with NNBSP + !, NBSP + ! or !, etc. 

(In the hypothesis of such a system it would be easy to add an option for those who would like to type the text exactly as it is written but who would not trust themselves not to yeld to temptation during training.)

I hope to move the thinking forward, and not confuse things more than necessary.

¹ By default LibreOffice uses NBSP for historical reasons but it’s configurable

**Comment by bragefuglseth** [comment]
Thanks for the input! We use the guillemets in Norwegian typography too, so I'm familiar with them. I agree that it would be cool if those could just be entered as typewriter quotation marks. 

In the system I'm fleshing out now, the app has a list of letters with "aliases", which are additional accepted ways to type those letters. When an alias has been fully typed, it's converted to the corresponding letter.

**Comment by bragefuglseth** [comment]
With the system I'm working on, we can at least alias non-breaking spaces to regular ones, and guillemets to typewriter quotation marks. An alias can only apply to a single letter, not sequences of them. The aliases themselves can (obviously) consist of more than 1 letter, though.

**Comment by bragefuglseth** [comment]
Happy to report that the rework has landed. This required quite a lot of new plumbing and string manipulation, so please let me know if there are any issues to iron out.

@idoric:

[French demo](https://github.com/bragefuglseth/keypunch/assets/91388039/0ec6529a-813b-421b-b5d3-d7d92977bc7c)

@developomp:

[Korean demo](https://github.com/bragefuglseth/keypunch/assets/91388039/fc0fabed-7e93-4457-8ed5-c1ad05948a63)
