### ISSUE TITLE
[Language Request]: Arabic

### ISSUE THREAD

**Issue by ibrahim-mu** [bragefuglseth/keypunch#3]
### English Name

Arabic

### Native Name

العربية

### Syntax

Arabic orthography is very different than languages that use the Latin alphabet. It is written from right to left, and the shape of a letter changes depending on its position in the word (stand alone or connected to following or preceding letters or both). There is no capitalization. Words are separated by a space. The punctuation marks ، ؛ : are used to connect clauses and sentences, and . ! ؟ to end sentences. Similar to English, punctuation marks are not preceded by a space but are followed by one. Expressions can be wrapped in parentheses ( ) or typewriter quotation marks " ".

### Implementation Assistance

- [X] I am proficient enough in this language to spot mistakes and unnatural words
- [X] I can assist with testing and reviewing the language implementation

### Additional Information

There are many variations of Arabic (e.g. Egyptian Arabic, Lebanese Arabic, Syrian Arabic, Moroccan Arabic), but the most common is the Traditional Arabic (or classic Arabic), which is the formal version used by speakers of all variants for news, paper work, emails, and formal essay writing. The orthography of the many other variants of Arabic is highly debatable since they underwent very little academic study and have less usage in formal writing than Traditional Arabic. Therefore I believe that including Traditional Arabic is enough.

**Comment by bragefuglseth** [comment]
Hi, there's an initial implementation on the main branch now! There are instructions in [CONTRIBUTING.md](https://github.com/bragefuglseth/keypunch/blob/main/CONTRIBUTING.md) on how to build and run the app from its source code. You can open the language dialog from the hamburger menu and choose Arabic from there:

![Skjermbilde fra 2024-05-24 11-59-14](https://github.com/bragefuglseth/keypunch/assets/91388039/a2508cae-4596-4fee-8eb2-3d3baea1b389)

The text isn't going to make much sense since it's all jumbled words anyways, but please do point out if something is wrong with the word list used. Since Arabic is so different from Latin scripts, there might also be some technical quirks. I'd be glad if you could point those out.

Oh, and the WPM reported *should* be accurate for Arabic as well, but if it seems way off the charts, we can try to fix that.

**Comment by ibrahim-mu** [comment]
I tried it. It works perfectly, and the way Lam Alef is done is not bad at all. The only problem I noticed about the word list is that it avoids Hamza (ء) and as a result avoids 4 or 5 letters أ إ ؤ ئ and replaces them with ا ا و ى ي which is both wrong and kind of weird, and I haven't found a word with letter آ (Alef Mamduda) but I assume it also gets replaces with ا.

**Comment by bragefuglseth** [comment]
Great to hear that it works! If you can pinpoint the weird words in the list, just list them here along with what they should be replaced with. I can just switch them out.

**Comment by ibrahim-mu** [comment]
[ar_SA.txt](https://github.com/bragefuglseth/keypunch/files/15443360/ar_SA.txt)
Here is the edited word list.

**Comment by ibrahim-mu** [comment]
Also do you think we can add words that only show in "advanced"? In Arabic (and Hebrew for example), you can add additional marks to letters to differentiate between two or more possible pronunciations of a word.
In the example عَلِم، عَلَم، عُلِم، عِلْم، عَلَّم، عُلِّم, all six words have the same letters Ayn, Lam, and Mim, but each one has a different pronunciation and meaning. This is not very common and people rely on the context of the word instead, but it can be nice to add only in the advanced level.

**Comment by bragefuglseth** [comment]
I'm not opposed to doing that, but the text view currently handles those additional marks rather poorly (you can try with a sample text and see it for yourself, the recoloring happens incorrectly and the app crashes after a few lines of text). I can look into the issue at some point in the future, but for now I'm inclined to keep the "simple" form in both modes :slightly_smiling_face:

**Comment by bragefuglseth** [comment]
The new word list is on the main branch now. Thanks for the help!
