### ISSUE TITLE
[Bug]: Bulgarian quotation should use „ “ instead of " "

### ISSUE THREAD

**Issue by UrtsiSantsi** [bragefuglseth/keypunch#41]
Under today's widespread English influence it is not uncommon to see " " used, but the correct one is „ “.

**Comment by bragefuglseth** [comment]
Is that what’s mostly used when typing on a keyboard as well? In Norwegian typography, one should really use the «guillemets», for instance, but what ends up actually being used are "these" because of their much more convenient key placement. Same for English, which has ”these“, but often ends up being written with "typewriter" quotation for the same reason. To avoid confusion, the generated text generally uses letters representing the actual keys.

If it’s common practice to use the keys representing „ and ” and it’s a habit people should internalize when typing Bulgarian, it can be changed, of course.

**Comment by twlvnn** [comment]
I think we should go with the English quotes. A stretch goal could be having a customization option to change the type of quotation character you can use for use cases as @UrtsiSantsi mentions, if you're practicing for professional work/academia. If users prefer the other quotes they might share their feedback about it. I think its best to get a good sample of users' feedback first and then we can revisit the issue . I tried looking at other apps to see how they tackle this problem but I didn't find a feature like that.

Official quotation marks are used primarily in handwriting, but I don't have any data to be sure what online users prefer. Bulgarians differ on keyboard layouts too (bg vs bg phonetic) where quotes are either on the 4 key or next to enter. The 4 key now gives you English quotes, [it used to give the Bulgarian quotes](https://en.wikipedia.org/wiki/Keyboard_layout#Bulgarian) but some got used to using 4 already so its difficult to find a sweet spot for everyone.

**Comment by twlvnn** [comment]
That's a perspective I can get behind and I think you bring up a fair point that feedback will be scarce, you're right that we should promote the correct use and users will benefit more from that in the long run than typing a little bit faster in the short term. Let's go with the official quotation marks.

**Comment by bragefuglseth** [comment]
Alright, I can go with that, but if I ever get an angry Bulgarian in this issue tracker asking why the app uses those, I'll ping both of you to argue with them :grin:

**Comment by bragefuglseth** [comment]
Mostly for consistency with «guillemet» quotation marks, which were proposed aliased to " in #22. It makes it possible to *optionally* use " and have it automatically corrected, since that’s what a word processor would do for you. It’s still possible to type „ and ” directly if you’d like to do it properly, of course.
