### ISSUE TITLE
[Language Request]: Hebrew

### ISSUE THREAD

**Issue by yoseforb** [bragefuglseth/keypunch#49]
### English Name

Hebrew

### Native Name

עברית

### Hebrew Alphabet:
- **Alphabet:** Hebrew has 22+4 (22 normal and 4 Sofit Letters) letters, all consonants. Vowels are usually not written but can be indicated with diacritical marks called "nikkud," though these are often omitted in everyday writing.
- **Direction:** Hebrew is written from right to left, unlike English, which is written from left to right.
- **Typing:** On a Hebrew keyboard, the letters are arranged differently from the QWERTY layout. Each key corresponds to a Hebrew letter, and there are no uppercase/lowercase distinctions for the same letter (since Hebrew does not use letter case).

### Word Separation:
- **Spaces:** Words in Hebrew are separated by spaces, just like in English.
- **Context:** Since vowels are often not written, context plays a significant role in understanding the meaning of words.

### Punctuation:
- **Common Punctuation:** Hebrew uses similar punctuation marks to English, such as periods (.), commas (,), question marks (?), and exclamation marks (!).
- **Placement:** While the punctuation marks are the same, they are placed at the end of sentences or phrases and follow the right-to-left direction of the text. For example, a period will appear at the far left of the sentence.

### Special Characters:
- **Geresh and Gershayim:** Used to indicate abbreviations and acronyms. The geresh (׳) is similar to an apostrophe and the gershayim (״) are like quotation marks but are placed before the last character of the abbreviation.
- **Sofit Letters:** Five Hebrew letters have a special form when they appear at the end of a word (kaf, mem, nun, pe, and tsade).

### Nikud:
- **Nikud:** These are diacritical marks used to indicate vowel sounds in Hebrew. They are primarily used in educational texts, poetry, and religious texts to ensure proper pronunciation. On a keyboard, typing nikud involves a combination of keystrokes and can vary depending on the keyboard layout.
- A word in Hebrew can be written with or without nikud (vowel marks). For example, the word "shalom" can be written as שָׁלוֹם (with nikud) or שלום (without nikud).

### Implementation Assistance

- [X] I am proficient enough in this language to spot mistakes and unnatural words
- [X] I can assist with testing and reviewing the language implementation

**Comment by bragefuglseth** [comment]
Hi, and thanks a lot for the language request! I've spun up an initial implementation, and you can test it by [building a development version of the app][build] and selecting Hebrew from the language switcher. Let me know if there are any problems with the text generation / input handling.

Since you mentioned the Nikud diacritical marks: Arabic has something similar, and while they're always omitted in the simple mode, the advanced mode contains some words with them. I got help from a native Arabic speaker that provided ~20 additional words with diacritical marks, and when "advanced" is chosen for Arabic, these are appended to the word list. We can do the same thing for Hebrew if you think it makes sense.

**Comment by yoseforb** [comment]
Thanks you, it works just fine.

For the Nikud issue, I think people not type Nikud blind, its very rare.

**Comment by bragefuglseth** [comment]
All right then! Thanks a lot for the help.
