### ISSUE TITLE
[Language Request]: Hindi

### ISSUE THREAD

**Issue by shellheim** [bragefuglseth/keypunch#6]
### English Name

Hindi

### Native Name

हिन्दी

### Syntax

Hindi is written in the devnagari script. Letters like क, ख, ग etc. It's the most spoken language in northern India and has presence in the rest of India. It has vowels like अ, आ, इ etc. which give signs to the consonants like आ + क = का, आ + ग = गा, इ + म = मि etc. 

These signs are called 'matras'. Consonants are without the 'अ' matra (generally not in listing them or in most words) and considered 'half'. The letter 'क' for example is pronounced 'kau' and has the sound of 'अ' (auo), without it there is a sign called a halant placed after a consonant looks like क् (could be any consonant ज् , ग् etc).

Sentences are ended with '।' called a 'purnaviram' (full stop) and it has all the other punctuation marks of English (!, ?, ;) and sentences are quoted with double quotes ("") and dubious/self-proclaimed things are enclosed in single quotes ('').

### Implementation Assistance

- [X] I am proficient enough in this language to spot mistakes and unnatural words
- [X] I can assist with testing and reviewing the language implementation

### Additional Information

If you implement hindi, everything is almost identical in marathi, nepali, odia, maithili etc. and these should be easier to implement.

**Comment by bragefuglseth** [comment]
Hi, the Hindi implementation is ready for testing! To check it out, download the [latest development build](https://nightly.link/bragefuglseth/keypunch/workflows/ci/main/keypunch-x86_64.zip) and choose "हिन्दी" in the language dialog. You should check if the words used are OK, and if the advanced text generation looks correct. There won't be any meaningful sentences since all the words are selected at random, but the punctuation should be on point.

If this looks good to you and I don't get any further feedback from the Nepali in #5, I'll probably close that issue as well, since Nepali uses the same code but with Nepali words.

**Comment by shellheim** [comment]
Every thing else is great but there are random numbers sprinkled in between text in advanced mode. 

![Screenshot_2024_06_08_59_52](https://github.com/bragefuglseth/keypunch/assets/116480892/70d0e632-bffb-47e1-8a76-14963da15cab)

**Comment by bragefuglseth** [comment]
That’s intentional, to make it possible to practice the number keys. Is there any reason it stands out to you? Should the behavior be dropped/changed for Hindi?

**Comment by shellheim** [comment]
Oh that's fine. Btw devnagari has its [own numbers](https://en.wikipedia.org/wiki/Devanagari_numerals), but it's not really used so I think the Arabic numerals are fine. Now I think we can close this issue.

**Comment by bragefuglseth** [comment]
Thanks a lot for the help!

**Comment by shellheim** [comment]
Just go with the github name "Shellheim". Thanks for the effort of putting Hindi in!
